version: '3.8'

services:
  db:
    image: postgres:15
    container_name: healthcare_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: healthcare_backend
    environment:
      DATABASE_URL: postgresql://postgres:admin123@db:5432/healthcare_db
      GROQ_API_KEY: ${GROQ_API_KEY}

      # GROQ_API_KEY: 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
      
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: healthcare_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: